'''SQL'''
/* Write your T-SQL query statement below */
SELECT 
NAME AS name, 
CASE WHEN USERS.ID = RIDES.USER_ID THEN SUM(DISTANCE) ELSE 0 END AS travelled_distance
FROM USERS LEFT JOIN RIDES ON USERS.ID = RIDES.USER_ID
GROUP BY USERS.ID,RIDES.USER_ID, USERS.NAME
ORDER BY SUM(DISTANCE) DESC, NAME ASC
